// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/huy/dev/TNM/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/huy/dev/TNM/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/home/huy/dev/TNM/index.ios.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('TNM', appParameters);
});